### ISSUE TITLE
[Life Infuser Issue]

### ISSUE THREAD

**Issue by Dream-Master** [Arcaratus/BloodArsenal#10]
Many Items from other Mods have now the Icon from your Life Infuser in Nei and sho in the hand as this ican also.

Some pictures.
https://www.dropbox.com/s/bvdcjfnm8pc79lj/Screenshot%202015-05-10%2015.24.02.png?dl=0
https://www.dropbox.com/s/f6wzl773gxbd6j2/Screenshot%202015-05-10%2015.24.04.png?dl=0
https://www.dropbox.com/s/tfxmzq5krkf2ck3/Screenshot%202015-05-10%2015.24.06.png?dl=0
https://www.dropbox.com/s/yj8fml983ndidr6/Screenshot%202015-05-10%2015.24.08.png?dl=0
https://www.dropbox.com/s/0swzbxkeuv57ir3/Screenshot%202015-05-10%2015.27.43.png?dl=0

What this mean ?

**Comment by Arcaratus** [comment]
Yeah, that's a bug that I need to fix, although I don't exactly know how though...

**Comment by Dream-Master** [comment]
I will ask my People on the Server maybe we find a solution.

**Comment by Arcaratus** [comment]
This issue will be fixed (already is) in the next update.
