### ISSUE TITLE
[1.10.2] Various crashes

### ISSUE THREAD

**Issue by MasterFee** [Arcaratus/BloodArsenal#103]
Already listed some occasions that cause crashes in a different [Issue (#101)](https://github.com/Arcaratus/BloodArsenal/issues/101).

Like I said there trying to place a Blood Infused Wood Slab Block crashes the game.
The latest crash occurs if I try to open the GUI of the Altare Aenigmatica.
Crash log: https://pastebin.com/jNULBmsd

**Comment by MasterFee** [comment]
I cannot insert items into the stasis plates, trying to force insertion with a hopper causes another crash. (Also: How does the Infusion de Sanguine crafting system work? Build the structure and I think I'm failing now because I cannot access the stasis plates.)
Crash log: https://pastebin.com/gGRMpipX

**Comment by Arcaratus** [comment]
The Blood Infused Wooden Slab issue might not be on my end (incompatibility with the Foam Fix mod?) and the last issue is just weird. Maybe try breaking and replacing the stasis plate to see if it fixes it.

The GUI and the item insertion bug is now fixed though.
