### ISSUE TITLE
[1.10.2] Random server crash

### ISSUE THREAD

**Issue by DV666** [Arcaratus/BloodArsenal#104]
Since the last update, i got some random server crash but i didn't know why....

Crash report avaible on this pastebin => [https://pastebin.com/ZPhT6ZpX](https://pastebin.com/ZPhT6ZpX)

(If i get more informations about that, i will update this case)

**Comment by ljfa-ag** [comment]
There are missing null checks on the item stacks [here](https://github.com/Arcaratus/BloodArsenal/blob/1.10/src/main/java/arc/bloodarsenal/util/handler/EventHandler.java#L87), and also in line 81. Possibly even more somewhere else.

**Comment by Arcaratus** [comment]
You'll have to forgive me for all these crashes because the 1.10.2 version was a backport of the 1.12 version. I'll get around to fixing it soon.

**Comment by DV666** [comment]
I have an example : when you throw an egg stack, the last will cause this crash.

**Comment by Arcaratus** [comment]
Should be fixed in the next version available very soon

**Comment by DV666** [comment]
Thanks Arcaratus :) I will waiting.
