### ISSUE TITLE
item in hand is not being null checked

### ISSUE THREAD

**Issue by Coolfeather2** [Arcaratus/BloodArsenal#105]
SpongePowered/SpongeForge#695

**Comment by Arcaratus** [comment]
Should be fixed in the latest version

**Comment by Coolfeather2** [comment]
SpongePowered/SpongeForge#1695
I gave wrong link, sorry

**Comment by Arcaratus** [comment]
This should still be fixed in the latest version

**Comment by Coolfeather2** [comment]
okay
