### ISSUE TITLE
Crash when mob ticked with soul snare caused by Blood Arsenal

### ISSUE THREAD

**Issue by Th3l0stSpart4n** [Arcaratus/BloodArsenal#106]
Only crashes server. Happened when a zombie got spammed with a snare, server now crashes upon login and loading of said zombie.
[crash-2017-08-05_11.02.29-server.txt](https://github.com/Arcaratus/BloodArsenal/files/1202465/crash-2017-08-05_11.02.29-server.txt)

**Comment by Arcaratus** [comment]
Should be fixed now in the latest version.
