### ISSUE TITLE
[Critical Bug] Items lost on death bug is still in the latest version.

### ISSUE THREAD

**Issue by PooPooUndees** [Arcaratus/BloodArsenal#109]
Maybe it has something to do with the configs or the modpack, I am using FTB Beyond for 1.10.2, the changelogs say that you fixed this issue in the latest version, which on curseforge is BloodArsenal-1.10.2-2.1.0-22.jar, however, I am still encountering this bug. Items are only lost when death is caused by the bleeding effect.

**Comment by Arcaratus** [comment]
Blood Magic version?

**Comment by PooPooUndees** [comment]
BloodMagic-1.10.2-2.1.11-80, which is the latest version on curseforge
