### ISSUE TITLE
Vanilla glass server-side crash.

### ISSUE THREAD

**Issue by FrozenPulse** [Arcaratus/BloodArsenal#11]
I experienced a server crash on my single-player world after breaking a vanilla glass block in survival. The glass was not stained, and was not a pane. 

I took the glass block from the creative menu. I then placed it down in survival and broke it. 
The world seed was 1970628762, and the worldgen type was Flatlands.

I think this crash might have something to do with the mod's 'glass shard' item not dropping properly.

Here is a pastebin link for the server crash log : http://pastebin.com/kqZ00DjJ

**Comment by Arcaratus** [comment]
On it

**Comment by Arcaratus** [comment]
Fixed.
