### ISSUE TITLE
Crash when inserting items to stasis plates

### ISSUE THREAD

**Issue by Cal26lum** [Arcaratus/BloodArsenal#112]
When inserting any item into the stasis plate, either by right click or with a hopper, the client crashes.

https://pastebin.com/0e1eGWkT

Blood arsenal 1.10.2-2.1.0-22
Blood magic 1.10.2-2.1.11-80

Am I correct in thinking that these plates are needed for the infusion de sanguine?

**Comment by Arcaratus** [comment]
Sorry for the late response!

The stasis plated are needed for the ritual. I'll check over the logs to
make sure it isn't an issue in the next version!
