### ISSUE TITLE
Incompatibility between BloodArsenal and Reika's VoidMonster on servers

### ISSUE THREAD

**Issue by ShayminKeldeo421** [Arcaratus/BloodArsenal#114]
I was getting an odd "A fatal error has occurred" kick when I tried to join a custom modpack server; when joining it, it would show the world for a split second, then kick me off. The game did not crash, meaning it was a server-side thing, so I decided to do some investigation as to what caused this. Looking in the client log revealed [this error.](https://hastebin.com/dayarodiba.css) Seeing as though it was an Entity ID mismatch, I used Anti ID Conflict to check the entity IDs on both the server and the client, which revealed a difference: the server list included BloodTNT but the client one did not. I created a new modpack with just DragonAPI, VoidMonster, BloodMagic, BloodArsenal, ExCore and AntiIDConflict and sure enough the error returned. The server worked fine with just BloodMagic/BloodArsenal. I also tried it without AntiIDConflict/ExCore and still got the error when the mods were paired.

So in conclusion, something with the EntityIDs messes up when the two are paired together, making servers unplayable due to this. I'm not sure what causes this specifically, but something prevents the EntityID of the BloodTNT from generating properly. Is there any way you can add a config option to set its EntityID manually?

[Client Entity List](https://hastebin.com/ocujisixaz.css)
[Server Entity List](https://hastebin.com/itororuqeg.css)

**Comment by Barhandar** [comment]
Specifically it fails to generate for client entirely. I suggest moving the code for assigning ID out of the CommonProxy.java and into BloodArsenal.java, specifically init phase.
