### ISSUE TITLE
[1.7.10][Gregtech New Horizons] Server crash when player used bound shears.

### ISSUE THREAD

**Issue by ProsperCraft** [Arcaratus/BloodArsenal#116]
https://gist.github.com/ProsperCraft/b8c4b2e4441fa5da0cbe71d84e07d4a3

The player used bound shears on a freshly grown oak tree leaves.

**Comment by TehNut** [comment]
Pretty sure Arc doesn't support 1.7.10.

**Comment by Arcaratus** [comment]
Yep, 1.7.10 is no longer supported.
