### ISSUE TITLE
[1.7.10] Crash while rigth-clicking with the bounded sheers causes server crash

### ISSUE THREAD

**Issue by chaos234** [Arcaratus/BloodArsenal#117]
https://hastebin.com/esepayemiv.sql

Even if 1.7.10 should no longer be supported but it would be fine to know why this crash happends?
I hope that there will be a solution even if it would take a while :)

**Comment by Arcaratus** [comment]
Some other mod or something else is doing some weird stuff to the Blood Hound entity which is never used once in the code. Puzzling indeed, but as you already know, 1.7.10 is not supported anymore.

**Comment by chaos234** [comment]
Can you tell me eventually what this "Blood Hound" entity is? Maybe I can go through the code myself and fix it myself, testing it and sending you a PR?

Would be nice if this would be ok @Arcaratus :)

**Comment by chaos234** [comment]
@Arcaratus - Found the Codeline directly which is easy to fix:

https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/items/tool/BoundShears.java#L238

Means, that the Bound Shears are trying to spawn your "Blood Hound" Entity which errors then compleatly out.

Reference:
https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/entity/mob/EntityBloodHound.java#L468

and

https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/entity/mob/EntityBloodHound.java#L196

If I now comment out L238 from the script above it should never ever call anymor the entity. To bad, since I want to know what kind of entity it is (hostile or not?) but what ever else is going wrong, it won't be spawned.

This is the only safe solution to this problem, maybe this is a possible reminder on the entity, since it is the only tool where this call is applied to.
