### ISSUE TITLE
Server Crash - MC 1.12.2 - 2707 + Blood Arsenal 1.0.21

### ISSUE THREAD

**Issue by MachinegunMarty** [Arcaratus/BloodArsenal#118]
Hi Arcaratus,

I got a crash on my server after updating blood arsenal to the latest BETA.

[FML]: An error occurred trying to load an EventBusSubscriber bloodarsenal for modid java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag

[latest.log](https://github.com/Arcaratus/BloodArsenal/files/2098773/latest.log)

Here is the log file of the server. It's says something about Applied Energetics to later on in the log, but i've been running that mod since i started the server.

I hope it helps you to locate the problem.

Good luck !

grtz,

MachinegunMarty

**Comment by Arcaratus** [comment]
Does this happen without Applied Energistics?

**Comment by TehNut** [comment]
There are several places where you use `@EventBusSubscriber` on an item class that overrides `addInformation(...)` without being annotated with `@SideOnly(Side.CLIENT)`. Also, your usage of `@EventBusSubscriber` is useless in all of these cases since the handlers are non-static and you're already registering the item instance to the bus.

**Comment by MachinegunMarty** [comment]
Hi Arcaratus,

I just tested this for you and unfortunatly, yes happens without Applied Energistics Rv3-Stable-11 to in the pack.

[FML]: An error occurred trying to load an EventBusSubscriber bloodarsenal for modid java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
[09:13:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag

I will attach my latest log without Applied EnergisticsRV3 here:

[latest 14-06-2018-913.log](https://github.com/Arcaratus/BloodArsenal/files/2101208/latest.14-06-2018-913.log)

Hope it helps you out.

Good luck !

grtz,

MachinegunMarty

**Comment by Arcaratus** [comment]
Thanks for reporting, everything should be fixed now, there is a new version available.

**Comment by MachinegunMarty** [comment]
I tried Blood Arsenal 1.0.22 and the server started without a problem !

Thanx for your hard work and the quick fix !


grtz,

MachinegunMarty
