### ISSUE TITLE
Server Crash on Startup due to latest version

### ISSUE THREAD

**Issue by mddawkins** [Arcaratus/BloodArsenal#120]
Arcaratus,

This crash happens when starting up a dedicated server using FoolCraft 3 1.3.1 (reuploaded) when the newest version of Blood Arsenal which is BloodArsenal-1.12.2-2.1.0-22.jar. While it does not happen when using BloodArsenal-1.12.2-2.1.0-20.jar.
The crash report is below.

[crash-2018-06-14_12.28.52-server.txt](https://github.com/Arcaratus/BloodArsenal/files/2103442/crash-2018-06-14_12.28.52-server.txt)

**Comment by TehNut** [comment]
@arcaratus, you *still* did not mark addInformation as client only.

**Comment by Arcaratus** [comment]
It should be fixed in the fixed version
plz dont kill me TehNut
