### ISSUE TITLE
Lightning Sigil not working on a dedicated server (1.12)

### ISSUE THREAD

**Issue by mddawkins** [Arcaratus/BloodArsenal#121]
The lightning sigil can be crafted but it cannot be used in multiplayer in the latest version (BloodArsenal-1.12.2-2.1.0-22.jar) while it can be used in singleplayer. Is there a configuration option because I did not see one.

Ways to reproduce.
1. Join multiplayer server
2. Use lightning sigil

**Comment by Arcaratus** [comment]
There might be a slight bug with the raytracing in the config files. Check the config for the raytracing option and make sure it is something not 0, I suggest 64

**Comment by mddawkins** [comment]
Thanks it was in the config it was at 0.0 by default

    # The max range for anything that uses raytracing (Ender Sigil, Lightning Sigil, etc.)
    # Min: 1.0
    # Max: 256.0
    D:rayTraceRange=0.0
