### ISSUE TITLE
[1.12.2] Tinkers' Construct Custom Materials Not Present

### ISSUE THREAD

**Issue by TechnoMysterio** [Arcaratus/BloodArsenal#122]
Blood Arsenal's custom material types for Tinkers' Construct tool components are not present. There's nothing in the 'Materials and You' book, nothing in JEI, etc. 

MC: 1.12.2
Forge: 14.23.4.2708
Blood Magic: 2.2.12-97
Blood Arsenal: 2.1.0-22
Tinker's Construct: 2.10.1.87

**Comment by Arcaratus** [comment]
Tinker's Construct integration is not yet available for 1.12.2
