### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [Arcaratus/BloodArsenal#13]
My game crash: (something with galactic Craft and your Mod)

https://gist.github.com/Dream-Master/84250aebc735406a1471#file-gistfile1-txt

The Texture bug i post before i never see again.

**Comment by Arcaratus** [comment]
Will take a look and the texture bug I am still working on. Thanks for reporting the crash!

**Comment by SunshineHunter** [comment]
I get this crash on my server whenever a player is next to spiders (Maybe more entities, but I didn't try it yet). Maybe, but it's not confirmed on my server yet, this causes a lot of World Tick too. 

 Please fix it as soon as possible!

**Comment by Arcaratus** [comment]
May have located the issue, testing now.

**Comment by Arcaratus** [comment]
Should be fixed, comment if it isn't!
