### ISSUE TITLE
[1.12.2] [2.1.0-23] Crash caused by Blood Arsenal during 4th loading stage

### ISSUE THREAD

**Issue by littlehav0c** [Arcaratus/BloodArsenal#131]
I was playing a modpack I'm developing (link below) and Blood Arsenal keeps causing it to crash during the fourth loading phase. This is also replicable if you go into twitch through a custom profile, adding only Blood Magic and Blood Arsenal, the same thing happens. The crash log from when I tried to load it in my custom pack is also below.
[JahYi's All Magic Pack-0.1.zip](https://github.com/Arcaratus/BloodArsenal/files/2291139/JahYi.s.All.Magic.Pack-0.1.zip)
[crash-2018-08-15_10.35.20-client.txt](https://github.com/Arcaratus/BloodArsenal/files/2291159/crash-2018-08-15_10.35.20-client.txt)

**Comment by wamc2017** [comment]
Update BloodArsenal to [1.12.2-2.1.0-24](https://minecraft.curseforge.com/projects/blood-arsenal/files/2587642).
