### ISSUE TITLE
Blood infused stairs placement

### ISSUE THREAD

**Issue by stevoace** [Arcaratus/BloodArsenal#135]
-The block placement direction is incorrect. And appears to affect the placement of all directional blocks (Stairs, furnace, tinker's controllers, pistons, etc [both vanilla and modded]). After removal of the mod the orientation of block placements are now correct.
-Once placed there is no step sound when walking on it. 
-Once placed it can be walked on but not broken.
-Block dissapears when another block is placed in the same block-space.

Noticed  "super(RegistrarBloodArsenalBlocks.BLOOD_INFUSED_WOODEN_PLANKS.getDefaultState());" in the stairs block class, getting blockstate of a block that is not being placed within the class??

**Comment by LemADEC** [comment]
Issue is still reproduced as of BloodArsenal-1.12.2-2.2.1-29 : can't break the block, can't interact with the top part of the stairs (even when placed on roof), block disappears when placing another block inside.

**Comment by Arcaratus** [comment]
Now in the latest version (1.12-2.2.1-30)!
