### ISSUE TITLE
Amulet of Sacrifice not usable while converting item

### ISSUE THREAD

**Issue by gazpachoking** [Arcaratus/BloodArsenal#136]
Trying to deposit the LP stored in the amulet of sacrifice while an operation is running in the blood altar just results in the amulet being placed back in the bauble slot. Was trying to create the Magician's Blood Orb, which requires more LP than my altar can hold, and figured the extra 10000 I had in the amulet would help.

**Comment by Arcaratus** [comment]
This is something inside of Blood Magic. I'll check and see if I can submit a PR to change it there.
