### ISSUE TITLE
Hard crash to desktop when using unbound Blood Orb on Altare Aenigmatica

### ISSUE THREAD

**Issue by wrincewind** [Arcaratus/BloodArsenal#144]
https://pastebin.com/gZJQz3dr log attached for reference.

In case it matters, I had the altare facing my blood altar from the side, and had previously bound it to my network before breaking and replacing it.

Incidentally, putting a blood orb into the orb slot of the altare apparently voids it, if there's already an orb in your blood altar.

**Comment by Arcaratus** [comment]
Thanks, should be an easy fix!

**Comment by Arcaratus** [comment]
Fixed in the latest version!
