### ISSUE TITLE
Issue with Ritual of Purification

### ISSUE THREAD

**Issue by pupnewfster** [Arcaratus/BloodArsenal#146]
Blood Arsenal version: 2.1.0-26
Blood Magic version: 2.4.0-102
Forge version: 14.23.5.2811

When trying to activate the ritual of purification, it says "A rush of energy flows through the ritual!" but it does not seem to actually activate. I used the ritual diviner to build the recipe and put the stasis plates and tanks in the same places the picture shows them on the CurseForge page. The top tank contains life essence, and the bottom one is empty. Is the ritual broken or is there something I am doing wrong?
![2019-02-07_15 58 15](https://user-images.githubusercontent.com/1203288/52442481-3bc8a180-2af1-11e9-95fe-d9dfd50b7cde.png)

**Comment by pupnewfster** [comment]
I can confirm that it is in fact broken. I compiled it and added some debug lines and it turns out it is unable to match the blood infused glowstone dust. So I am looking a bit to see if I can come up with a fix and then PR it.

**Comment by Arcaratus** [comment]
I will look at it right now

**Comment by pupnewfster** [comment]
Ok, the first issue is that `EnumBaseTypes.BLOOD_INFUSED_GLOWSTONE_DUST.getStack()` is being added as AIR to PURIFICATION_1. I believe because it does not actually exist as an item when the ritual is registered. Moving it to performRitual (if it has not already been set) causes it to properly start. Still doing some testing to see if that is enough to get the ritual to start properly or if there are some other issues remaining.

**Comment by Arcaratus** [comment]
I think I'll just stick into the ModRecipes class for now.
