### ISSUE TITLE
Crashing NPE On BloodArsenalEventHooks.onEntityDamaged

### ISSUE THREAD

**Issue by KaneHart** [Arcaratus/BloodArsenal#15]
Added your mod today and starting to crash none stop related to this: http://pastebin.com/Q1xppUGy

From what I can tell seems like Entity doing damage or player doing damage to a Entity it has a chance to trigger this crash. 

EDIT: Happens none stop had to remove the mod sadly. Everytime our friend logins it crashes here is that crash I assume exact crash as above:
http://pastebin.com/RwBF6SDA

**Comment by Noobsloth** [comment]
Can confirm this error happens on the latest version. Here's an additional log : http://pastebin.com/UrvWiKCc

**Comment by Arcaratus** [comment]
Will be fixed today in the latest version
