### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by PulzHF** [Arcaratus/BloodArsenal#152]
Seems to be a dupe of #141 

https://paste.dimdev.org/xezubejiva.mccrash

Forge: 2784
Blood Arsenal: 2.2.0.27
Blood Magic: 2.4.0.102

Thanks.

**Comment by Arcaratus** [comment]
Hmm, this might sound lame but does retrying it fix the issue?

**Comment by PulzHF** [comment]
> Hmm, this might sound lame but does retrying it fix the issue?

Yes, I have attempted several times included fresh installation. 
I can give you access to the development modpack version at https://www.technicpack.net/modpack/tc-redux if you provide your IGN- if you'd be interested in checking yourself.

**Comment by Pulz-TCP** [comment]
Just as a quick update- this is not a version specific issue- but a compatibility issue with one of the mods I've recently added.
I'll post back once I've figured out the offender.

**Comment by Pulz-TCP** [comment]
The issue occurs only when [FastFurnace ](https://minecraft.curseforge.com/projects/fastfurnace)is present. I'll pass on this information to them.

**Comment by Pulz-TCP** [comment]
> Possibly a result of BA incorrectly handling replacements? Nothing I can do about it from my end.
-FastFurnace developer

**Comment by LemADEC** [comment]
Issue is not reproduced with 
BloodArsenal-1.12.2-2.2.1-29
FastFurnace-1.12.2-1.3.1
BloodMagic-1.12.2-2.4.3-105
forge-14.23.5.2836
