### ISSUE TITLE
Class Not Found Exception Crash on Startup

### ISSUE THREAD

**Issue by ASolitaryBird** [Arcaratus/BloodArsenal#153]
Newest update crashed my modpack immediately. I think it's trying to look for Tinkers Construct but I don't have that in my pack.
[BloodAresnalCrash.pdf](https://github.com/Arcaratus/BloodArsenal/files/3098545/BloodAresnalCrash.pdf)

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/nuxosadese.mccrash

Can confirm.

**Comment by Arcaratus** [comment]
Fixed, there is a new file on Curse now with the fix.
