### ISSUE TITLE
Stasis Tools and Modifier Tomes

### ISSUE THREAD

**Issue by TrirdKing** [Arcaratus/BloodArsenal#156]
The stasis tools by themselves seem pretty worthless so I assume that you need the modifier tomes to make them the lategame weapons that they are supposed to be(considering the effort and ressources they require to make) but there is no documentation whatsoever on how to aquire said modifiers. Neither in-game nor on the internet, I've tried skimming through the code but couldnt find anything there either and considering this is a noticeable part of the content the addon has I'd consider this quite the issue. 
So I'd like an explanation how said modifiers are aquired and what stasis tools can do so I can add the info to a wiki so others dont have to deal with this.

**Comment by Arcaratus** [comment]
The Curse page has been updated with a lot more documentation!
https://www.curseforge.com/minecraft/mc-mods/blood-arsenal
