### ISSUE TITLE
1.12.2 TiC Casting Issue

### ISSUE THREAD

**Issue by Dustalis** [Arcaratus/BloodArsenal#157]
The blood infused iron can be molten in the smelter, however it cannot be cast into any parts or even back into an ingot. It should be noted that there isn't any recipe that the molten version is used for in jei, and therefore no way to obtain the parts. I checked the config for Blood Arsenal and Tinkers' and was unable to see any options that should apply to the issue except Arsenals: tconstructCompatEnabled which was set to true.

Minecraft: 1.12.2
Forge:14.23.5.2821
Blood Arsenal: 1.12.2-2.2.0-28
Tinkers': 1.12.2-2.12.0.135

If you need any other information on mods  or such I am using the latest release of this:
https://minecraft.curseforge.com/projects/dark-age-of-dys/files

![PartBuilder](https://user-images.githubusercontent.com/50548596/57583846-67657a00-749a-11e9-87d9-d56cbfbd5d95.png)
![Materials](https://user-images.githubusercontent.com/50548596/57583848-67fe1080-749a-11e9-98df-f24f0b77962e.png)
![Book](https://user-images.githubusercontent.com/50548596/57583849-67fe1080-749a-11e9-8f72-7587c0f5c393.png)
![Molten](https://user-images.githubusercontent.com/50548596/57583850-67fe1080-749a-11e9-80e0-e954ed8063dd.png)
I know that it shouldn't be usable in the part builder but felt I should test it regardless.
To reclarify the problem is no matter what I try when I right click the faucet it doesn't come out despite other metals casting just fine. I have only gotten it to cast into the seared tank.

**Comment by Arcaratus** [comment]
Working fine now
