### ISSUE TITLE
Infusion De Sanguine Modifiers apply to Handles, not Heads.

### ISSUE THREAD

**Issue by rudger-wolvram** [Arcaratus/BloodArsenal#158]
I got the Infusion De Sanguine to work for adding modifiers, however, it appears it only applies to the Handle and not the Blade itself. I followed what was in JEI for Razor Sharp 6, 54 of everything with 24 iron ingots, etc. Threw the blade in "sheathed" like in JEI, hit the MRS, ritual completes, only takes some ingredients. 45 and 16 left respectively out of 54 and 24 for each item stack.

Once complete I found the +8 attack on the handle item, not the blade. So when i unsheath it, it falls back to it's default 7.7 attack. 

I threw down a target dummy, did 9 points with the handle and 7.7 with the blade. So it definitely applied to the handle itself as an item. I'm going to try the ritual with a new blade and unsheathed to see if it makes a difference and comment my results. It probably will make a difference, but as for issues, if this is intended, it never should have worked with the blade sheathed.

You can see the state of the blade in the top and bottom left of the screenshots.

This is the stats on the sheathed blade
![StasisHandle](https://user-images.githubusercontent.com/2502240/57663018-c836a480-75b7-11e9-9bce-c5812e5c2dc0.PNG)

This is the stats on the unsheathed blade (same item as above)
![StasisBlade](https://user-images.githubusercontent.com/2502240/57663040-e0a6bf00-75b7-11e9-9568-2cf121a3dd72.PNG)

**Comment by rudger-wolvram** [comment]
I created a brand new stasis sword, unsheathed it, slapped it in the ritual for a razor 6, it popped out, but the effect only still applies to the handle and not the blade itself. Oh, and i did have to reboot the server to make the ritual work. That's part of the infinite LP drain issue.

**Comment by rudger-wolvram** [comment]
I tested this on a stasis pickaxe with Razor 6 as well, it worked just fine and applied in both deactivated and activated states. So it seems to be just a minor bug with the blade itself. I've not tested with the shovel or axe yet.

**Comment by Arcaratus** [comment]
Fixed in the latest version (1.12-2.2.1-30)!
