### ISSUE TITLE
Tinkers' Construct Living Modifier Not Working

### ISSUE THREAD

**Issue by Vva70** [Arcaratus/BloodArsenal#159]
The Living and Living II modifiers for TiCo tools do not seem to be functioning. I created a Minecraft instance with only Blood Arsenal, Blood Magic, Tinkers' Construct, JEI, and dependencies. I tested tools of both blood infused wood and iron, each tool made fully out of the material. No durability was repaired, nor was any LP drained from the soul network. Non-TiCo blood infused tools work fine.

Mods/Versions:
Minecraft 1.12.2
Baubles 1.12-1.5.2
Blood Arsenal 1.12.2-2.2.0-28
Blood Magic 1.12.2-2.4.0-102
Guide-API 1.12-2.1.8-63
JEI 1.12.2-4.15.0.279
Mantle 1.12-1.3.3.55
Tinkers' Construct 1.12.2-2.12.0.135

**Comment by Arcaratus** [comment]
Not sure if this was fixed accidentally, but seems to work
