### ISSUE TITLE
friendly reminder about Tc and BA intergration

### ISSUE THREAD

**Issue by Papapayana** [Arcaratus/BloodArsenal#16]
start up issue D: heres the pastebin links :) hope this help it always happens on start up when BA is added into the mix

http://pastebin.com/XQAAw55c

http://pastebin.com/SbbhYxbK

http://pastebin.com/X4Zy0mER

**Comment by Arcaratus** [comment]
Looks like TiCTooltips and EnderIO also error as well but...I'll take a look.

**Comment by Papapayana** [comment]
:D cool really looking forward to using this mod ^_^
