### ISSUE TITLE
Blood Burner Rites not working

### ISSUE THREAD

**Issue by Aimiks** [Arcaratus/BloodArsenal#160]
Hello,

The rituel "blood burner rites" is not working after having one successful use of the ritual. I tried the ritual with a small amount of blood in the tank, full lava tank, one glowstone dust on stasis plates and the ritual sucessfully worked. But after that I wanted to put more inputs in it, so I fullfilled every container, put stacks of blood infused glowstone and finally activate the ritual, but nothing happened. There is the text showing that the ritual has been successfully activated but the ritual does not end (show any explosion) and do nothing. 

Also it appear that putting a Bound Igniter instead of a regular Igniter does not work and make the ritual exploding (ending)

My setup
![image](https://user-images.githubusercontent.com/34943215/61258213-c4b8c880-a774-11e9-84eb-c09edcd51a3e.png)

ver 1.12, modpack : Ragnamod V

**Comment by Arcaratus** [comment]
Fixed in the latest version (1.12-2.2.1-30)!
