### ISSUE TITLE
Ligthning Reagent not working?

### ISSUE THREAD

**Issue by duncanwebb** [Arcaratus/BloodArsenal#163]
Is the lightning reagent not working in BloodArsenal-1.12.2-2.2.0-28

I have the following build and the lighting bolt strikes the water but nothing happens to the ingredients. The water source block contained six items that are binding reagent, glowstone block, block of gold, block of redstone and block of iron and a gunpowder.

![2019-11-13_15 26 23](https://user-images.githubusercontent.com/4198031/68772774-ae3f5280-062a-11ea-90f6-ac553645bb1d.png)

Am I missing something?

BloodArsenal-1.12.2-2.2.0-28
BloodMagic-1.12.2-2.4.2-104

**Comment by duncanwebb** [comment]
Using a water source block didn't work either.

![lightening-reagent](https://user-images.githubusercontent.com/4198031/69008182-f078d480-0947-11ea-90a6-e0f1e2874a71.gif)

**Comment by JayCee23** [comment]
Lightning from rituals don't count, they aren't actually lightning.

**Comment by duncanwebb** [comment]
So, what does this mean, it is almost impossible to acquire a lightning reagent. The chances of lightning hitting a specific block before the items de-spawn is almost zero. Do you know of a systematic method to get lightning to strike in an area?

Many thanks.

**Comment by JayCee23** [comment]
Other mods often add something that causes lightning in an area. I don't know of anything in Blood Magic that would help. I think this may have been built off of features in Blood Magic that have since been removed.

**Comment by duncanwebb** [comment]
Thank you, I think you're correct there are quite a few features that have been removed from the 1.12 version. Summoning a thunderstorm does really work, it makes the sky black and produces thunderclaps but no lightning.

**Comment by Arcaratus** [comment]
There's an Imperfect Lightning Ritual that Blood Arsenal adds- Place an Iron Block onto the Imperfect Ritual Stone and it will strike the top with lightning

**Comment by duncanwebb** [comment]
Thank you for this information it helps a lot.

I'll make another [episode of my Blood Arsenal series](https://youtu.be/ICj8PSSRaZo) with this information. There were quite a few high-level rituals and items that I couldn't get to work. If you get a chance would you be so kind as to help me out?
