### ISSUE TITLE
[1.12.2-2.2.0-29] Serrated and sentient tinkers modifier are absent

### ISSUE THREAD

**Issue by Hermsmegerms** [Arcaratus/BloodArsenal#165]
Issue: two modifiers listed on the mod page are absent from the game

Details: I am playing within FTB Revelations with 1.12.2-2.12.0.157 version of Tinker's Construct. The living and Living II modifier show up and appear to work as expected, however the other two modifiers do not. 

Reproduce: Install FTB Revelations Add blood arsenal. Search JIE for the modifiers. Or, simply try to create an item with Glass shards, or greater tartaric gem

Expectation: The weapon will gain the serrated or sentient modifier
Result: the modifier does not apply and does not appear to exist. 

Perhaps there is something i am not understanding about how they should work but i feel they are not present in the current version of blood arsenal.

**Comment by Arcaratus** [comment]
There was a change in the way things were being registered in some mod - it's been fixed now

**Comment by Arcaratus** [comment]
Fixed in the latest version (1.12-2.2.1-30)!
