### ISSUE TITLE
[1.12.2-2.2.0-29] Crystal cluster recipe missing.

### ISSUE THREAD

**Issue by SpoilersMC** [Arcaratus/BloodArsenal#166]
I saw in a previous version of the mod that a temporary recipe for crystal cluster blocks was added to make crafting the divinity sigil possible but it seems that recipe has been removed or lost in the most recent updates making the reagent unobtainable, is there something that needs to be added to the config to bring this recipe back? is the recipe just hidden somewhere? or is my only option adding a custom recipe through craft-tweaker.

**Comment by Arcaratus** [comment]
The recipe has been removed for reasons and will not be added back in.

**Comment by runescapejon** [comment]
@Arcaratus I hope it's no issue at all if i may ask, why was this remove any particular reason?

**Comment by runescapejon** [comment]
I hope it's not an issue of me asking, what is the reasoning as to why it's been removed?
