### ISSUE TITLE
Blood Hound issue

### ISSUE THREAD

**Issue by devryb** [Arcaratus/BloodArsenal#18]
It seems there's a blood hound spawned around coordinate 0 0 causing players to get internal server error whenever they try to interact with something in the world no matter where they are.  (I'm guessing coordinate 0 0 is loaded all the time by default since its near spawn)
However the only reason I found it was that spot as when I go near it the server actually crashes instead of the client getting internal server error

When players interact with something this error is shown in the log:
http://pastebin.com/iPxiyhUK

Here is the server crash report when someone goes near the 0 0 coordinates:
http://pastebin.com/9D6xiQ6U

I managed to fix this on my own by loading up a world with just the region file for that coordinate and the level.dat file with Blood Arsenal disabled.
Flew around the area a bit then stopped the server and replaced the region file from that on the main server.  Both the internal server error and crash went away after that.

**Comment by Arcaratus** [comment]
Yea...forgot to un-implement that...Will fix it next version.
