### ISSUE TITLE
Bound Bow cannot be enchanted in Vanilla Enchanter

### ISSUE THREAD

**Issue by WBittner** [Arcaratus/BloodArsenal#19]
According to NEI the bound bow can be enchanted with, among other things, infinity - and in your code I can see you check if it has the infinity enchant to see if it needs arrows to shoot, however I cannot place it in the enchantment table. Is this a bug or is there some other intended way to put infinity on the bow?

EDIT: To clarify, it can be placed in the table, it just that no enchantments show up to enchant it with.

**Comment by Arcaratus** [comment]
Tis vanilla Minecraft: I'll look for a work around to see if I can do something about it.

**Comment by WBittner** [comment]
I figured as much. I know a bit of java and I've tried to look around and see if I noticed anything different about the way other mods created/added bows and I've found that pretty much every mod does pretty much everything differently, so that's hardly helpful. If it makes your life any easier, I know that you can enchant [Thermal Foundations bows](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/item/Equipment.java), so maybe you can pick up something there that I cannot? I appreciate you looking into this, and so far I've loved your add on!

**Comment by Arcaratus** [comment]
I'll take a look

**Comment by Arcaratus** [comment]
Fixed! I was missing the method isItemTool (don't ask me why it wasn't in the ItemBow class)
