### ISSUE TITLE
Transparent Orb Stops Rendering After A Certain Amount

### ISSUE THREAD

**Issue by RoloEdits** [Arcaratus/BloodArsenal#21]
When Its Close To 60 million LP It Stops Rendering

![2015-07-10_21 51 33](https://cloud.githubusercontent.com/assets/12489689/8632402/69c9c30c-274e-11e5-8190-207c14920342.png)

![2015-07-10_21 51 39](https://cloud.githubusercontent.com/assets/12489689/8632403/6e025da8-274e-11e5-974e-3896095f8aaf.png)

**Comment by Arcaratus** [comment]
Well, it's only supposed to hold 30 mil, actually, now that you say that, let me check

**Comment by RoloEdits** [comment]
I Should Have Mentioned That I Was Using The Orb From Forbidden Magic That Holds 80 Million To Fill Up My Network.

I'm Sorry.

**Comment by RoloEdits** [comment]
But If Supposed To Be How You Said Even At 30 Million it Was Not Even Half Way Full On The Rendering

**Comment by Arcaratus** [comment]
No, I have an idea why it's like that

**Comment by Arcaratus** [comment]
Fixed!

**Comment by RoloEdits** [comment]
Sweet, thank you very much :)

**Comment by Arcaratus** [comment]
Actually, it wasn't fixed since Forbidden Magic has not updated its orb code. Let me see what I can do about that
