### ISSUE TITLE
Crash with fakePlayer

### ISSUE THREAD

**Issue by Namikon** [Arcaratus/BloodArsenal#25]
Heya,

we're getting this crash on our Server as soon as the chunk is loaded:
`java.lang.ClassCastException: thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at com.arc.bloodarsenal.common.BloodArsenalEventHooks.onEntityDamaged(BloodArsenalEventHooks.java:78)`

Could you add an instanceof check to that cast?

**Comment by Arcaratus** [comment]
Will work on it

**Comment by Arcaratus** [comment]
Just fixed thanks to @TehNut!

**Comment by Namikon** [comment]
I just created a pull request that explains and fixes the issue

**Comment by Arcaratus** [comment]
Fixed
