### ISSUE TITLE
Crash after updating

### ISSUE THREAD

**Issue by lilmoefow** [Arcaratus/BloodArsenal#28]
I updated to the recent release available on Curse Voice and now im gettin crashes. Seems to be something with the thaumcraft integration??? 

Here's a crash log:
http://pastebin.com/sTrJBidi

**Comment by TehNut** [comment]
#27

**Comment by lilmoefow** [comment]
guess i should have checked the closed issues first :P

**Comment by Arcaratus** [comment]
Go grab the latest one on Curse! Should be fixed!

**Comment by lilmoefow** [comment]
I did, Thanks for the quick fix.
