### ISSUE TITLE
This Requires Thaumcraft?

### ISSUE THREAD

**Issue by Kyrinon** [Arcaratus/BloodArsenal#30]
when I try to load your mod with out thaumcraft I get this error "NoClassDefFoundError: thaumcraft/api/wands/IWandRodOnUpdate" I have tried to load this mod with only blood magic installed and get the same error. it would seem that it is unnecessarily reliant on thaumcraft. I am using version 1.2-2

**Comment by Arcaratus** [comment]
I know the issue and it will be fixed.

**Comment by Kyrinon** [comment]
thank you
