### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Fortist** [Arcaratus/BloodArsenal#31]
1) The Compactor shouldnt eat the orb used when compacting, 
2) Recipes need to be worked on, a lot of it is extremely tedious (Blood Diamonds) or just not worth it (Lightning Sigil)
3) Textures are straight garbage.

Luckly, other than the first one, I can change/fix most of these things.

**Comment by Arcaratus** [comment]
Compacter eats the orb part of lore and for balance purposes. Compacted things are quite OP.
Recipes are still undergoing changing for balance purposes etc.
Textures.....maybe I'll redo some......maybe....
