### ISSUE TITLE
java.lang.NoClassDefFoundError: thaumcraft/api/wands/IWandRodOnUpdate

### ISSUE THREAD

**Issue by Ricket** [Arcaratus/BloodArsenal#32]
I am playing FTB Horizons Daybreaker and tried to update the version of Blood Arsenal. This modpack does not contain Thaumcraft, but it appears the latest version of Blood Arsenal tries to load it anyway. It crashes on startup. I opened BloodArsenal.cfg and changed `B:"Enable Thaumcraft/Forbidden Magic integration?"=false` and it still crashes with the same error. Error log is at: http://pastebin.com/En4AVcXL

**Comment by TehNut** [comment]
#30

**Comment by Arcaratus** [comment]
The new release is out as of.....now!
