### ISSUE TITLE
at com.arc.bloodarsenal.common.misc.VersionChecker.onTick(VersionChecker.java:34)

### ISSUE THREAD

**Issue by AHrubik** [Arcaratus/BloodArsenal#33]
Crash on world creation or world entry.

FTB Horizons II: Daybreaker 1.0.2 and 1.1.0
BloodArsenal-1.7.10-1.1-12 and 1.1-14
Repeatable: Yes

Pastebin: http://pastebin.com/rGSh6YME

Updating to BloodArsenal-1.7.10-1.2-2 causes another crash.

Pastebin: http://pastebin.com/X83y062q

removing Blood Arsenal fixes the issues.

**Comment by TehNut** [comment]
Your first issue is irrelevant since you're insanely outdated. The second issue was just fixed: #30 and #32

**Comment by AHrubik** [comment]
Thanks. The outdated can't be helped since there hasn't been a Horizons II:Daybreaker release in awhile. Do you know when 1.2.3 will be available for download? It's not on the Curse site yet.

**Comment by sabarjp** [comment]
Neither removing the mod or updating to 1.2.3 fixes the issue on my server. Both actions introduce a torrent of errors and mismatched IDs.

I don't understand why everything worked fine then one day it all breaks out of the blue :(

**Comment by Arcaratus** [comment]
Eh?

**Comment by AHrubik** [comment]
For transparency removing BloodArsenal did fix my issue. I tried to update it to what was available at the time (1.2.2) but in the end it was easier to remove it and wait for the pack to update. Instructing multiple users to delete and download an updated version is cumbersome at best.

I'll be happy to have BloodArsenal in the pack when it updates if everything works as intended.

**Comment by ProsperCraft** [comment]
Crashing all of my users as well, removing from my server too.

**Comment by jaz000** [comment]
Have this as well, custom modpack with BloodMagic-1.7.10-1.3.3-13

Everything was working fine and then suddenly no one can log into the server - the client crashes ~(not tried creating local world)

http://pastebin.com/Gqapj6de

Looks like something in the version check creating the client crash? Can't disable version check in the client config?

**Comment by jaz000** [comment]
https://raw.githubusercontent.com/Arcaratus/BloodArsenal/master/version/1.7.10.txt
responds with "1.2-3" is that right? I am on 1.3.3-13
I tried to break the version check with a host file entry pointing raw.githubusercontent.com elsewhere but it would appear with that down a whole bunch of mods break!

**Comment by Arcaratus** [comment]
Blood Arsenal 1.1-14 users need to update to the latest one to fix the VersionChecker crash.
Note that if you're playing Horizons, it was recently updated so no need to worry.
