### ISSUE TITLE
Compacting Demon Age Ritual

### ISSUE THREAD

**Issue by Keridos** [Arcaratus/BloodArsenal#37]
We have compacted the ritual and got the demon base block but after placing it it did not do anything.

BloodArsenal-1.7.10-1.2-4

**Comment by Arcaratus** [comment]
Did you activate it, set it up exactly as it would for the ordinary ritual (placing correct jars and transferring essences into it?).

**Comment by Keridos** [comment]
Actually I think the player who did it may have forgotten to do the demon sacrifice.

**Comment by Arcaratus** [comment]
Everything should theoretically work the same way, so there must be in error somewhere on your end.
