### ISSUE TITLE
Ethereal Blood Stone returns Potentia when crafted

### ISSUE THREAD

**Issue by PokeMaserJ** [Arcaratus/BloodArsenal#38]
Version 1.7.10-1.2-4

**Comment by Arcaratus** [comment]
Care to elaborate...?

**Comment by PokeMaserJ** [comment]
Sorry, haven't checked my email in a while, but the crafting output for 1 Ethereal Blood Stone is 9 Potentia. To make it takes 9 Ethereal Slates, like it should, BUT if you try to uncompress it, it turns into 9 Potentia.

**Comment by Arcaratus** [comment]
Probably a mistype in the metadata code...
