### ISSUE TITLE
ポケモン! pokemon...? pokemon?!?! wot...

### ISSUE THREAD

**Issue by plaguewolf** [Arcaratus/BloodArsenal#41]
[23:57:33] [Client thread/ERROR] [BloodArsenal]: ポケモン!
[23:57:33] [Client thread/ERROR] [BloodArsenal]: java.lang.ArrayIndexOutOfBoundsException

so, yeah.... dunno, no other details were given.

**Comment by Arcaratus** [comment]
Hermma herma.....potion ID's did not manage to register properly! Don't know why that happened, you may have some things tinkering around with potion ID's?

**Comment by plaguewolf** [comment]
reika's dragonAPI extends potion ID's to 256, so, that might do it.

**Comment by plaguewolf** [comment]
so, wait. here: https://github.com/Arcaratus/BloodArsenal/blob/e37470040c04c804674096b4e19b1b4f9ca363fe/src/main/java/com/arc/bloodarsenal/common/BloodArsenal.java#L104 are you also modifying the max potion ID array? cause that would certainly explain why things are derping.

**Comment by Arcaratus** [comment]
That portion of code is a standard for any mod that adds in potions normally to extend the Potion array if needed, *shouldn't* be causing any problems
