### ISSUE TITLE
Blood Infused Ingot

### ISSUE THREAD

**Issue by AeroyrHwrdd** [Arcaratus/BloodArsenal#42]
The Blood Infused Ingot recipe from this mod clashes with that of the sacrificial ingot in Technomancy. Minetweaker at the ready? Not ore dict compatible so cannot swap one for the other, the sacrificial ingot is made first. Any idea in what way to tweak this?  Change one of the ingot recipes? Or simply disable one ingot and change the recipes they are included in?

**Comment by Arcaratus** [comment]
Err, you can use Minetweaker and set the LP cost for the sacrificial ingot to be the same as the blood infused iron ingot and make a recipe converting between the two? Can't really do OreDict with Blood Magic's altar...
