### ISSUE TITLE
Portable Altar Block Crash

### ISSUE THREAD

**Issue by Nuclearsmilz** [Arcaratus/BloodArsenal#43]
Alright. So. 

First things first, the crash log:
http://pastebin.com/EVqq0tgv

Secondly, I've read some stuff on the MC Forum about this issue, no solutions. At first, I did not mind crashing and relaunching over and over. But now, especially that I am mid game and trying to do stuff, opening my inventory and crashing is not fun. At all. Can you please. Please. try and figure something out? Because I can't remove the mod because it is a HQM pack. 

Anyways I know you work hard so just try and figure this one out? :)

thanks

**Comment by TehNut** [comment]
@Arcaratus Why are you [reading the `capacity` tag as a String](https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/items/block/PortableAltarBlock.java#L38)? You don't set it as a string *anywhere* in the code.

**Comment by Arcaratus** [comment]
Woops...

**Comment by Nuclearsmilz** [comment]
xD so would this fix it? and not to be a pushover.. but if it does, when can you get a build out? :^)

**Comment by Arcaratus** [comment]
1.7.10 is no longer getting any updates sorry, I'm working on 1.9 right now

**Comment by Arcaratus** [comment]
New release: http://minecraft.curseforge.com/projects/blood-magic-addon-blood-arsenal

**Comment by Nuclearsmilz** [comment]
*sigh*....


ok. Not even this pretty annoying crash?

On Mon, Mar 21, 2016 at 6:29 PM, Arcaratus <notifications@github.com> wrote:

> Closed #43 <https://github.com/Arcaratus/BloodArsenal/issues/43>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Arcaratus/BloodArsenal/issues/43#event-597882078>
>



-- 
Jon

**Comment by Arcaratus** [comment]
?

**Comment by Nuclearsmilz** [comment]
Omg hahahah you did it!!! Thanks!!

On Mon, Mar 21, 2016 at 7:03 PM, Jon Marien <nuclearsmilz@gmail.com> wrote:

> *sigh*....
>
>
> ok. Not even this pretty annoying crash?
>
> On Mon, Mar 21, 2016 at 6:29 PM, Arcaratus <notifications@github.com>
> wrote:
>
>> Closed #43 <https://github.com/Arcaratus/BloodArsenal/issues/43>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Arcaratus/BloodArsenal/issues/43#event-597882078>
>>
>
>
>
> --
> Jon
>



-- 
Jon

**Comment by Nuclearsmilz** [comment]
you, or someone released a build fixing it.

--
Jon
