### ISSUE TITLE
Version notification

### ISSUE THREAD

**Issue by Mattsingen** [Arcaratus/BloodArsenal#44]
I'm using BloodArsenal-1.7.10-1.2-5 in my own Curse custom pack. When launching I get a warning that 1.2-5 isn't the current version, 1.2-4 is.
It isn't anything game breaking... Just to let you know.

![image](https://cloud.githubusercontent.com/assets/11715240/14059530/2a5b08ee-f344-11e5-91f7-b80a0a863ed6.png)

**Comment by Arcaratus** [comment]
Uh...might've messed up the versioning somewhere..

**Comment by Arcaratus** [comment]
Fixed!
