### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by drewbit** [Arcaratus/BloodArsenal#47]
Didn't happen on client when I launched. I'm pretty sure I have all the libraries I need so I have no idea why I'm getting this error, here's the log:

http://pastebin.com/pwZngKgr

BloodMagic: BloodMagic-1.9.4-2.0.1-40
BloodArsenal: BloodArsenal-1.9.4-2.0.0-2
Forge: forge 1.9.4-12.17.0.1935-1.9.4

**Comment by TehNut** [comment]
10/10 arc https://github.com/Arcaratus/BloodArsenal/blob/1.9/src/main/java/arc/bloodarsenal/registry/ModItems.java#L56

**Comment by Arcaratus** [comment]
Am I not supposed to be doing that...
