### ISSUE TITLE
Client crash on Server when viewing Dragon Mounts Entities

### ISSUE THREAD

**Issue by Himeki** [Arcaratus/BloodArsenal#48]
Compatibility problem.
Forge dedicated server, version 1566.
Minecraft version 1.7.10
Java 1.8.0_31
Blood Arsenal ver. 1.2-3

[Crash Log](http://pastebin.com/uXUkTuKp)

If the mod is used with "[Dragon Mounts](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1439594-dragon-mounts-r43-wip)" version r42. Upon placing and right clicking the egg (causing it to start hatching), and any login afterwards, the Client will crash. (server keeps going without error)
SSP works normally, no crashing.

[ChocoCraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2269183-1-8-clienthaxs-chococraft-2-happiness-distilled) version 4.1.5 also experiences some issues with rendering. Yellow chocobo's specifically show up invisible and spam the console with rendering errors.

Both issues are solved by removing Blood Arsenal.

**Comment by Arcaratus** [comment]
Even though 1.7.10 is not supported, I'll try recommending that you update Blood Arsenal to 1.2-5 and seeing if that works
