### ISSUE TITLE
Life infuser Interaction with Thermal Expansion Energy cell

### ISSUE THREAD

**Issue by Kadell** [Arcaratus/BloodArsenal#50]
Tested only the leadstone energy cell, but putting it into the life infuser converts it from the empty leadstone energy cell (2359:1) into a Creative Energy Cell (2359). A black list of items that cannot be inserted could help prevent this in the future when other bad interactions are found.

**Comment by LemADEC** [comment]
Issue happens with any block with metadata, this is a critical issue.

**Comment by LemADEC** [comment]
Issue seems located here: https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/tileentity/TileLifeInfuser.java#L249
We're missing a check that the item has no sub-types before going further (i.e. calling getHasSubtypes()).

**Comment by TehNut** [comment]
I don't believe Arc intends to work on the 1.7 version of this mod anymore.

**Comment by LemADEC** [comment]
Life infuser has been removed in 1.9 ?

**Comment by TehNut** [comment]
I'm not seeing it on the 1.9 branch. So probably.
