### ISSUE TITLE
[Server 1.9.4 Crash] Points to Blood Arsenal

### ISSUE THREAD

**Issue by APolarBaer** [Arcaratus/BloodArsenal#51]
http://pastebin.com/V52vucxL

Just updated blood arsenal
fresh world
doing nothing

**Comment by Arcaratus** [comment]
I updated Blood Arsenal 2.0.0-10, see if that fixes it

**Comment by APolarBaer** [comment]
i havent been able to reproduce it so only time will tell >w< but i will update asap and let you know if it happens again, thank you~
