### ISSUE TITLE
Hard dependency on Baubles

### ISSUE THREAD

**Issue by mezz** [Arcaratus/BloodArsenal#54]
BloodArsenal crashes when Baubles is missing. 
Please change `after:Baubles` to `required-after:Baubles` 
https://github.com/Arcaratus/BloodArsenal/blob/1.9/src/main/java/arc/bloodarsenal/BloodArsenal.java#L24

**Comment by TehNut** [comment]
I assume you want this on the 1.9 branch and not the 1.7?

**Comment by mezz** [comment]
Yeah, found it while testing for BTM

**Comment by Arcaratus** [comment]
Wait, is there anyway to make sure that Blood Arsenal loads after Baubles? Or is that not a thing anymore in 1.10

**Comment by TehNut** [comment]
You are correctly loading after baubles. The problem is that you're doing bauble stuff even if baubles is not installed.

**Comment by TehNut** [comment]
@Arcaratus http://paste.ubuntu.com/19424661/
