### ISSUE TITLE
crash with the new BloodMagic version

### ISSUE THREAD

**Issue by Hypsellis** [Arcaratus/BloodArsenal#55]
I get this crash with the 2.0.3-51 BloodMagic version. http://pastebin.com/gF8ist3M

**Comment by TehNut** [comment]
Maybe give him more than 30 minutes to update..?

**Comment by Arcaratus** [comment]
Lol, you're quick, I'm updating as we speak

**Comment by StevenTheEVILZ** [comment]
When will this be on curseforge?

**Comment by Arcaratus** [comment]
It will be once Im done

**Comment by StevenTheEVILZ** [comment]
:)! K

**Comment by StevenTheEVILZ** [comment]
Also, can you please tell curseforge that your mod is compatible with (I think it works) 1.10.2? TY

**Comment by EnderT5** [comment]
https://gist.github.com/EnderT5/dcacd73588a1118e9a63fd2483c13100

same crash happens to me

**Comment by Drakray** [comment]
is there plan to backport the fix for 1.9.4?

**Comment by Arcaratus** [comment]
1.9.4 will be indirectly supported. Meaning, that if Tinker's Construct
(has to be the 1.10.2 version) is used, then it will not be 1.9 compatible.
If you don't use Tinker's Construct then you can try and see if 1.9 works.
There will be no direct backport as such.
