### ISSUE TITLE
Lightning Reagent recipe is missing

### ISSUE THREAD

**Issue by jkneuf** [Arcaratus/BloodArsenal#63]
I am using BloodArsenal-1.10.2-2.0.1-11 and there is no JEI recipe for the Lightning reagent. So I peeked around at your code trying to find what the recipe should be and it looks like there is no recipe for it at all in the ModRecipes.java file. The Divinity Reagent  recipe shows that the Lightning Reagent is a component, but no way to get the Lightning Reagent.

**Comment by Arcaratus** [comment]
https://minecraft.curseforge.com/projects/blood-arsenal?comment=16
