### ISSUE TITLE
Blood-infused Iron, Living modifier, and TiC Problem

### ISSUE THREAD

**Issue by zlyfire** [Arcaratus/BloodArsenal#65]
Using Blood Magic 2.0.3-54, Blood Arsenal 2.0.1-11, Forge 12.18.1.2065, and Tinkers' Construct 2.0.4.jenkins312.

I had crafted a tool rod of the blood-infused iron, so as to get the Living II modifier, and put it on my pickaxe. It took awhile for me to notice, but even when my pickaxe was fully repaired, my LP was still getting drained 100 at a time. I had no rituals, and nothing to drain LP from my soul network aside from that modifier. I don't think it's intended for Living II to continuously drain LP from your soul network, or is it?

**Comment by Arcaratus** [comment]
Uhh...I don't think the Blood-infused iron is supposed to be craftable yet unless I derped up somewhere, and the Living modifier is still WIP but will look into this. Thanks for reporting!

**Comment by zlyfire** [comment]
I did craft it, a ludicrous amount of blood went into each ingot!
But no problem, I report what I can whenever it needs to be!
