### ISSUE TITLE
Ticking player crash.

### ISSUE THREAD

**Issue by Claycorp** [Arcaratus/BloodArsenal#67]
http://pastebin.com/ZCv8teRa

**Comment by Arcaratus** [comment]
Did you get the version off of jenkins or compiling it by yourself off of Github (if you did when)?

**Comment by Claycorp** [comment]
I got nothing from a jenkins or from compiling it myself. I can't use it on curse unless the dev updates the mod.

**Comment by Arcaratus** [comment]
Umm.... so where did you get the version? I have not released a version with that name at all.

**Comment by TehNut** [comment]
Your latest build was made locally. Since you copied the BM script, it will then use `-CUSTOM`.

**Comment by Arcaratus** [comment]
It did? Whoops, will take a look at it
