### ISSUE TITLE
[1.10.2][Forge 2075] Crash With Latest Blood Magic

### ISSUE THREAD

**Issue by Hastling** [Arcaratus/BloodArsenal#69]
http://pastebin.com/271DFCmx

**Comment by TehNut** [comment]
Info: I rewrote the key binding system because, no offense Arc, yours was horrible.

**Comment by MakerTim** [comment]
http://pastebin.com/2pbq1cT0
same error

**Comment by Arcaratus** [comment]
On it

**Comment by erindalc** [comment]
If people are waiting on a fix, roll back Blood Magic to build 56
