### ISSUE TITLE
[1.10.2]Crash at launch

### ISSUE THREAD

**Issue by LotuxPunk** [Arcaratus/BloodArsenal#70]
Hello, can you help me please ? :)

http://pastebin.com/bi17gtb9

**Comment by TehNut** [comment]
This has literally nothing to do with Blood Arsenal.

**Comment by LotuxPunk** [comment]
I've seen `UCE BloodArsenal{1.10.2-2.0.1-CUSTOM} [Blood Arsenal] (BloodArsenal-1.10.2-2.0.1-11.jar)`

But ok, I tried to help you.

**Comment by Arcaratus** [comment]
Yeah, this has nothing to do with Blood Arsenal... Might want to direct it at the mod author of Wired? Haven't heard of the mod so don't know who it is.

**Comment by LotuxPunk** [comment]
OK, I go to see that, thank you ! ;)
