### ISSUE TITLE
[1.10] Crash with latest version

### ISSUE THREAD

**Issue by MakerTim** [Arcaratus/BloodArsenal#71]
There is a newer version of BloodMagic
(yea i know of the older report, but in last 3 days is there a new version, so new point where code breaks)
and code is not compatible anymore

http://pastebin.com/VsEtUy5Z

**Comment by Arcaratus** [comment]
Oh boy...I'll get right to it

**Comment by MakerTim** [comment]
http://pastebin.com/huA4MLxb

Still the error, and BloodMagic has a Release not a alpha/beta anymore

**Comment by Arcaratus** [comment]
Been working on it
