### ISSUE TITLE
[1.10] Blood infused wooden log not craftable

### ISSUE THREAD

**Issue by MakerTim** [Arcaratus/BloodArsenal#72]
I got a Tier IV altar, 9060 LP
but the log recipe is not working for me...
http://puu.sh/rz2YF.jpg

No particles, no effects, no LP draining or something
The recipe in JEI is showing logWood, as far i know din't support BloodMagic support OreDic recipes in bloodaltar, but that could be wrong from my on
either way, its not crafting.
was not working in previous versions

---

Forge 1.10.2-2094
Blood Magic 2.1.0-65
Blood Arsenal 2.0.1-11

**Comment by Arcaratus** [comment]
Should be fixed, was a Blood Magic API thing that I did not code properly.
