### ISSUE TITLE
[1.10.2] Please add a way to automatically trigger rituals

### ISSUE THREAD

**Issue by 666lumberjack** [Arcaratus/BloodArsenal#73]
I have a modpack in the works that uses Blood Magic's custom meteors for all ore generation and other stone-type blocks. However, I'd like for players to be able to fully automate resource gathering eventually, and this presents a problem since there's no way in base Blood Magic to automatically trigger the ritual and the Blood Magic devs don't want to allow fake players to do it. 

What I'm hoping you might be able to add is some kind of block that when given an activation crystal and a redstone signal will activate the MRS it's attached to for some cost. Perhaps it could drain will from the chunk somehow to incentivise going into that stuff?

**Comment by WayofTime** [comment]
Um, dude, it's planned for the base BM mod for there to be a way to reactivate the meteor ritual. Please be patient.
