### ISSUE TITLE
[1.10.2-2.0.1-13] Molten Blood Infused Iron liquid has no texture when placed in world

### ISSUE THREAD

**Issue by SPMoo66** [Arcaratus/BloodArsenal#74]
https://u.pomf.is/gppwms.png

**Comment by Arcaratus** [comment]
Umm...I didn't even know it had a block texture!

**Comment by SPMoo66** [comment]
I believe it's added by Tinkers' Construct as a result of having material support

**Comment by Arcaratus** [comment]
Will look into it although I believe it's still WIP
