### ISSUE TITLE
Client kicked from server when taking damage

### ISSUE THREAD

**Issue by darkphan** [Arcaratus/BloodArsenal#75]
When a user takes certain damage the client gets disconnected from the server and the server logs indicate this http://pastebin.com/zPPeEksL ... appears Blood Arsenal needs to be updated to support current versions of Baubles.

**Comment by Arcaratus** [comment]
Hmm...seems like Baubles updated yesterday, will need to go take a look at that!

**Comment by Mattsingen** [comment]
I got a crash that I think is the same issue. 
[http://pastebin.com/MmJVLv16](http://pastebin.com/MmJVLv16)
I updated to the new beta version of Baubles as Vazkii had update Botania. Botania also had crashes with references to the PlayerHandler.

**Comment by Arcaratus** [comment]
Expect a release sometime next week

**Comment by Vaeyr** [comment]
Hello! Thought about posting a new issue, but it may be somewhat related so here it is : I can't seem to be able to hit any entities (animals/mobs), and whenever a mob hits me, it crashes. Without Blood Arsenal I can hit again.

In the last changelog from Blood Magic there's that : 
Version 2.1.0-65:
- Fixed NPE when attacking mobs when you don't have a set of Living Armour. Oops.
Don't know what it means, but who knows, might give some lead? 

Cheers!

**Comment by KaneHart** [comment]
Looking forward to this. Released my pack going to remove it now since I want my other mods updated.

**Comment by Arcaratus** [comment]
Should be fixed along with the Baubles incompatibility!

**Comment by Tridon343** [comment]
Having a very similar crash: http://pastebin.com/RHnHWvgz
Whenever the player receives damage the game crashes (tried several versions of baubles)
Also I am unable to damage mobs. Neither modded nor vanilla weapons work. I see a swing animation but it doesn't damage anything.

Removing blood arsenal solves the issue.
