### ISSUE TITLE
Crashing Client At Random? {Possible API Issue With Bubbles}

### ISSUE THREAD

**Issue by KaneHart** [Arcaratus/BloodArsenal#78]
I just started testing and was in creative mode but I think I hit something that could of caused damage. Either way this is the error log:

http://pastebin.com/5j4RMqVp

Seems like a API Issues with bubbles?

Just to update what triggered the damage even though none happen was a dot damage from poison ivy. Not sure if that info is needed lol but there you have it.

**Comment by TehNut** [comment]
#75

**Comment by BrelanAllin** [comment]
Same situation. Any beta bauble version causes random crashes and sometimes you simply can't deal any damage attacking.
