### ISSUE TITLE
(Compatability) Crash with latest Baubles

### ISSUE THREAD

**Issue by ZiggyAdventures** [Arcaratus/BloodArsenal#79]
Just a friendly notice that Babules-1.10.2-1.3.BETA9.jar causes crashes in-game with BloodArsenal-1.10.2-2.0.1-13.jar

A few packs have been posting crashes so figured I'd give you a heads up.

http://pastebin.com/pn4CWRat

**Comment by TehNut** [comment]
#75

**Comment by ZiggyAdventures** [comment]
Ah my mistake. I mostly saw it when helping others with crashes so did not know it was on taking damage and didn't investigate.
