### ISSUE TITLE
crash with new blood magic and new baubles

### ISSUE THREAD

**Issue by tiarnia** [Arcaratus/BloodArsenal#81]
java.lang.IllegalArgumentException: No enum constant WayofTime.bloodmagic.api.soul.EnumDemonWillType.corrosive
[B#347]  	at java.lang.Enum.valueOf(Unknown Source)
[B#347]  	at WayofTime.bloodmagic.api.soul.EnumDemonWillType.valueOf(EnumDemonWillType.java:7)
[B#347]  	at arc.bloodarsenal.compat.baubles.ItemSoulPendant.getCurrentType(ItemSoulPendant.java:328)
[B#347]  	at arc.bloodarsenal.compat.baubles.ItemSoulPendant.func_77624_a(ItemSoulPendant.java:197)
[B#347]  	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:614)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:367)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:345)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:523)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:296)
[B#347]  	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:573)
[B#347]  	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:527)
[B#347]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
[B#347]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[B#347]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[B#347]  	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Arcaratus** [comment]
#75

**Comment by TehNut** [comment]
No, this is not a dupe.

**Comment by Arcaratus** [comment]
Oh well, the bug is fixed regardless
