### ISSUE TITLE
Crash with latest blood magic.

### ISSUE THREAD

**Issue by The-Key** [Arcaratus/BloodArsenal#83]
With blood magic 2.1.0-68 and 2.1.0-67 we get this crash when picking up a demon will after using the snare. Downgrading bm to 2.1.0-66 fixes it.

https://cdn.discordapp.com/attachments/247991806288068609/253976147082215428/crash-2016-12-01_20.58.16-server.txt

**Comment by Arcaratus** [comment]
Thanks for reporting! Will be doing a release within the next week (or sooner)!

**Comment by The-Key** [comment]
Sure, thanks for responding so quick. If you need more info, I'm happy to oblige.
