### ISSUE TITLE
[1.7.10 - IMPORTANT!!!] - Crash with Enderquarry and BM

### ISSUE THREAD

**Issue by chaos234** [Arcaratus/BloodArsenal#86]
As stated here: https://github.com/Arcaratus/BloodArsenal/compare/master...Namikon:patch-2 there was a fix but the 1.7.10 version for this was never official released and now it is no longer possible to start up the server because the announced jenkins build is gone way.

Even if 1.7.10 is no longer supported but this hotfix should be released for 1.7.10 as fast as you can please, otherwise we are not be able to continue to play on our private server which is horrible at this moment.

If u want a crash report I can provide this.

**Comment by Arcaratus** [comment]
If you need the fix that badly, just edit the code (which you've already
done) and compile it by yourself, because it's not that hard. In fact I
believe there are instructions on the main Github page of the repo. But
1.7.10 builds are not going out and that's a final decision by me.

**Comment by chaos234** [comment]
That is bad even if I understand your decision.

Well, then I'll take a look in the GTNewHorizons MP and grab the file from there,
Is a bit faster as forking and compiling the project on my own side.

But thanks for your fast replay.
