### ISSUE TITLE
1.10.2 Blood Infused Iron/Smeltery

### ISSUE THREAD

**Issue by Urijahuri** [Arcaratus/BloodArsenal#88]
Okay I've tried everything I can think of to smelt Blood infused iron, but it will not melt in a smeltery.

I've attempted this with nothing but bare bones mods (only dependencies) but I cannot make TiC tools with this material despite recipes existing.

For my sake and the sanity of the people who play with me on my custom modpack, is this feature broken or just not implemented yet? everything seems complete from what I see.

**Comment by Arcaratus** [comment]
Version?

**Comment by Urijahuri** [comment]
2.0.1-17

**Comment by Urijahuri** [comment]
If it matters heres the versions of the other mods.
Blood Magic 2.1.4-73
TiC 2.6.3

**Comment by Arcaratus** [comment]
I'm going to do some bug testing and report back to see what I find. Might be just that I've done it but never released a version that has it implemented.

**Comment by Urijahuri** [comment]
fair enough, The blood infused wood works fine, albeit only in plank form. but it appears as though the information to smelt the blood infused iron ingots is missing and rendering it impossible to craft TiC tool parts from it.

I did a bit of other testing as well and it appears as though you cannot melt down any of the tool parts either, making the molten version impossible to get without spawning it in.

**Comment by kotoroshinoto** [comment]
I have not been able to do anything with the blood infused iron at all either using 2.0.1-17 and blood magic  2.1.6-75 with tconstruct 2.6.3

**Comment by kotoroshinoto** [comment]
I tried editing the recipes back in with minetweaker, but all the tool casting recipes end up as arrowheads for some reason. That is probably a bug with the tconstruct handler so i'm not going to blame that result on blood arsenal, however the not being able to work with the metal in the smeltery IS probably the fault of this mod.

**Comment by egypt** [comment]
I'm having the same problem in FtB:Beyond; Blood Arsenal 2.0.1-17, Blood Magic 2.1.7-76, Tinkers Construct 2.6.3

**Comment by Reygok** [comment]
This is still an issue in the current version of FTB Beyond, 1.10, with Tinkers 2.6.5, Blood Magic 2.1.11-80 and Blood Arsenal 2.0.1-17

**Comment by Arcaratus** [comment]
There has been a newer version released (2.1.0-22) which might fix the bug although it is up to the people managing FTB Beyond to update it unless you want to do it yourself. If I recall correctly though it was an issue on Tinker's side, unsure if that's still the case.
