### ISSUE TITLE
transparent orb

### ISSUE THREAD

**Issue by nailfor** [Arcaratus/BloodArsenal#89]
when i bind the Orb to myself, orb change his name to "unnamed" and don't show blood in LP
mc 1.7.10, ba 1.2-5

**Comment by Arcaratus** [comment]
1.7.10 bugs are no longer being worked on but there's probably an issue with how you bind items.

**Comment by nailfor** [comment]
i'm bound the orb with shift-left click. But i have Eldritch Blood Orb from Forbidden Magic with addition Rune of the Orb on the Altar.
After that Transparent Orb changed his name for "unnamed"i'm bind orb with shift-left cloick. But i have Eldritch Blood Orb from Forbidden Magic with addition Rune of the Orb

**Comment by Arcaratus** [comment]
You have to bind items with a right-click. It should damage you to indicate
it's working.

**Comment by nailfor** [comment]
Yes, it damage me, but NOT working. I don't see level my LP.
I'll look into the source code...
