### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by 100chilly** [Arcaratus/BloodArsenal#9]
http://pastebin.com/pnzZvJ6w
https://paste.ee/p/CkF76

Edited to included server log.

Please let me know if you can fix this.

**Comment by Arcaratus** [comment]
Hmm, tested and it works, so it's most likely something with your current setup since the pointers don't show anything...

**Comment by 100chilly** [comment]
I'm looking into it right now but the only thing that really pops out to me is blood arsenal in the crash log. i'll keep digging though :)

**Comment by mrdeadlocked** [comment]
I have this same crash on updating blood arsenal on my server client has no problems same updates. 100chilly- you ever find anything out?

**Comment by apotheoseGrifter** [comment]
http://hastebin.com/serumotodu.profile

I have an exactly identical error, with only 26 mods in common and different forge versions. No idea what could be causing the problem, but perhaps it could be narrowed to an interaction between this mod and one of those mods? In any case, I don't have the time right now to troubleshoot, so in case anyone else does, these are the mods I have in common with 100chilly:

AOBD
Baubles
Bibliocraft
Blood Arsenal
Blood Magic
Botania
Camping Mod 2
Carpenters' Blocks
Chisel
CodeChickenCore
CoFHCore
DenseOres
Enchiridion
GuideAPI
JABBA
LunatriusCore
Mantle
Mariculture
Mine and Blade: Battlegear 2
NotEnoughItems
OpenBlocks
OpenModsLib
Rikmuld's Core
Sanguimancy
Twilight Forest
VeinMiner

**Comment by TehNut** [comment]
The culprit is [this](https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/items/bauble/EmpoweredSacrificeAmulet.java#L56) line. You're calling the client world on the server.

**Comment by Arcaratus** [comment]
Ah, I'll fix it now, thanks TehNut!
