### ISSUE TITLE
Unable to create spikes

### ISSUE THREAD

**Issue by iKurama** [Arcaratus/BloodArsenal#90]
Mod version: BloodArsenal-1.10.2-2.0.1-17

I am unable to make spikes, right clicking, shift clicking or dropping them?

**Comment by Arcaratus** [comment]
I'm unsure what you mean by spikes. You mean individual Glass Shards (as in the item) or the block?

**Comment by xenxero1** [comment]
If its the Glass Shards block, I believe its crafted with glass shards in a 9x9.

**Comment by Arcaratus** [comment]
That is indeed the crafting recipe.
