### ISSUE TITLE
two sigils crash when used

### ISSUE THREAD

**Issue by kotoroshinoto** [Arcaratus/BloodArsenal#91]
client crashes when I try to use swimming sigil or sigil of divinity.

might be a bug in basecode of blood magic, as some of those sigils crash me, but I figured i'd give you a heads up.

**Comment by Arcaratus** [comment]
I can't do anything without a crash report, Blood Magic and Blood Arsenal,
and Forge versions.

**Comment by kotoroshinoto** [comment]
when I play again later on i'll reproduce both crashes and pastebin them for you.

for the ones you asked about:

blood-magic,2.1.4-73,
blood-arsenal,2.0.1-17

forge 1.10.2-12.18.3.2185

liteloader is in there too in case it matters.

if you want to toss the set of mods i'm using together I can send you a link to the config and zipfile of my multimc instance. (I wouldn't want to make that public though, as the instance has a listing to the private server I'm running with personal friends.)

**Comment by kotoroshinoto** [comment]
blood magic has updated to 2.1.6-75, so I will probably update immediately after I reproduce the errors and record them to see if that repairs the issue. I'll let you know once I have done this. (my friends usually get on in the evening, and I don't have time to play right now even for testing purposes.)

**Comment by kotoroshinoto** [comment]
oddly, the crash didn't present itself again this time around.

Even though it happened three client loads in a row last time.

(similar to the bugs I was experiencing with the base blood magic sigils)
