### ISSUE TITLE
[1.7.10] causing crashes due to mismatched entity id's 

### ISSUE THREAD

**Issue by TylorBane** [Arcaratus/BloodArsenal#92]
Hello, I'm not sure if you can help me with this or if you are even willing to, but blood arsenal is doing some funky stuff on a 1.7.10 server I'm working on. I'm not sure if its another mod I'm using or what else might be going on, but what I do know is this, I use anti-id-conflict for 1.7.10 and was able to track down the source of the problem, but I'm not sure how to fix it. Any time the server would want to spawn a wither skeleton, it would force any player's nearby to crash-log (exit out of the server but not actually crash either the client or the server with a msg on the client saying "a fatal error has occurred, connection has been terminated") I look at the latest.log produced by the client at the time and it was saying it was enderIO's custom withers causing the issue, and I knew that couldn't be true as I've been using enderIO for ages. Long story short, I took a look through anti-id-conflict on both the server and client for entities, and end up seeing that blood-tnt isn't being registered as an entity on the client and thus causing an id-mismatch via other mods as they retrogen their id's to be the lowest possible, and having blood-tnt missing halfway through, causes other things behind it to move one id up. anyway, not sure if there's anything you can do, but that's the issue I'm having.

**Comment by Arcaratus** [comment]
I can't really help you there since 1.7.10 is no longer being supported.
However, if you can somehow manage to disable the entity of Blood TNT
(using another mod or compiling a custom build with the entity disabled)
then it should be fixed.

**Comment by TylorBane** [comment]
out of curiosity why is 1.7.10 no longer being supported? there are a lot of mods that are no longer updating that can only be found on 1.7.10... its really disappointing... i'd move to a higher version but... i cant have all my mods...

**Comment by Arcaratus** [comment]
1.7.10 is outdated due to there being more updated Minecraft versions that
are supported by Forge meaning modders write their mods for the updated
version instead of staying on a non-updated version. It's also the modder's
choice whether or not they want to continue to update their mod.

**Comment by TylorBane** [comment]
alright, fair enough, *shrugs* i just wanted to know your reasoning behind it is all, thanks for the information though :P don't know if i'll be able to get it fixed but, i'll certainly try. :wave:
