### ISSUE TITLE
Items in inventory deleted when dying from glass sacrificial dagger

### ISSUE THREAD

**Issue by SpeedySpy52** [Arcaratus/BloodArsenal#93]
No gravestone, or if there is a gravestone there are no items in it...
Just lost all my stuff due to this bug.

**Comment by Arcaratus** [comment]
Might have something to do with [this](https://github.com/WayofTime/BloodMagic/issues/1106).

**Comment by Arcaratus** [comment]
Fixed in the latest version!

**Comment by crazyirishwrencher** [comment]
Just had it happen on my multiplayer server to one of my players.
