### ISSUE TITLE
Blood Diamond causing crash

### ISSUE THREAD

**Issue by WinterAU** [Arcaratus/BloodArsenal#94]
The blood diamond causes crash. 
Crash Log: https://pastebin.com/TWZAWdxy

Blood Arsenal: 2.0.1-14
Minecraft Version: 1.10.2
Forge Version: 12.18.3.2254
FML: 8.0.99.99

Edit: 
The blood diamond seems to have caused the world to not load. 
Here is the [log](https://pastebin.com/jQP8c28L)

**Comment by Arcaratus** [comment]
When does this happen?

**Comment by WinterAU** [comment]
I should've specified.. whoops. 

The crash happens when you're crafting the blood diamond it's self. Multiplayer servers are safe because of the rollback that comes with a crash but singleplayer worlds seem to just, crash.

**Comment by Arcaratus** [comment]
Confirmed and testing, seems to actually be a Blood Magic bug but will report back with more details.

**Comment by heyoomimi** [comment]
I recently also experienced this issue on our multiplayer server with the same crash report. Was wondering if there have been any updates on this bug.

**Comment by WinterAU** [comment]
@heyoomimi it's an issue with blood magic, so if you want to make a post on /WayofTime/BloodMagic/ outlining what's happening I'd be greatful as I'm not currently at my desktop.

**Comment by Arcaratus** [comment]
Fixed in the latest version due to me changing the recipe, although I should really go fix this on Blood Magic's side as well.
