### ISSUE TITLE
Lightning reagent

### ISSUE THREAD

**Issue by rocketmonkey45** [Arcaratus/BloodArsenal#95]
Hello,

I'm having a slight problem getting lightning reagent. Following the directions you have given in the past, block of red stone, gold, iron, ETC. into water and striking it with lightning results in the items being consumed, but no reagent drop. ive tried this several time using both vanilla lightning ( using a command for 3/5 attempts) and using a the thunder caller from Botania for a further 2 attempts. I am currently using the latest version of Feed The Beast Beyond, but i just wanted to check whether this is a issue with the base mod, or if it is a fault of the pack itself.

Many thanks
RocketMonkey45

**Comment by Arcaratus** [comment]
Has been fixed in my local repo.

**Comment by d3athwolf** [comment]
well in 1.4.2 beyond i was able to make lightning reagent did realise there was a trick to it as you need to be fast on picking up the reagent other wise it disapears with in moments but i did find it alittle odd that i got like 6 - 7 reagents at once happen to me a few times only used like 3 or 4 sets of blocks and i already had more than 32 needed for divinity sidgil

**Comment by Arcaratus** [comment]
Fixed in the latest version!
