### ISSUE TITLE
[2.0.1-17] Soul Pendant not recognised by Sentient Sword/Bow/Armour when in Bauble slot

### ISSUE THREAD

**Issue by Babbie** [Arcaratus/BloodArsenal#98]
As it says in the title, if you make any type of Soul Pendant and equip it, any items in your inventory that run on will won't see the will contained inside and will become depowered.

**Comment by Arcaratus** [comment]
I'm not sure this is fixable without some hacks, but then again, I'm also open to hacks...
I'll see if I can do anything about it next version.
