### ISSUE TITLE
[1.7.10] Crash when placing Sigil of Holding in Life infuser

### ISSUE THREAD

**Issue by aking4125** [Arcaratus/BloodArsenal#99]
Client insta crashes when right clicking with the sigil of holding. Also seems to be with the sigil of the blood lamp.
[crash-2017-07-02_19.00.24-client.txt](https://github.com/Arcaratus/BloodArsenal/files/1120117/crash-2017-07-02_19.00.24-client.txt)

https://pastebin.com/Jf6mzXKu

**Comment by Arcaratus** [comment]
Sorry but 1.7.10 is no longer supported. You'll just need to not do that
specific action.

**Comment by aking4125** [comment]
Alright
